#!/usr/bin/env bash

# Check what system we are on
system_type=$(uname -s)

# Check if we are root
sudo -v

# install nerdfonts
if [ "$system_type" = "Darwin" ]; then
    brew tap homebrew/cask-fonts
    brew install --cask font-hack-nerd-font
elif [ "$system_type" = "Linux" ]; then
    mkdir -p ~/.local/share/fonts
    # Download nerd fonts and save in ~/.local/share/fonts
    curl --output-dir ~/.local/share/fonts/ -fLO https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/HackNerdFontMono-Regular.ttf
    curl --output-dir ~/.local/share/fonts/ -fLO https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/HackNerdFont-Regular.ttf
fi

# Install fish shell
if [ "$system_type" = "Darwin" ]; then
    brew install fish
elif [ "$system_type" = "Linux" ]; then
    sudo -v
    echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:3.list
    curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg >/dev/null
    sudo apt update
    sudo apt-get install -y fish
fi

fish -c "curl -sL https://git.io/fisher | source &&  fisher update"

# change default console to fish
if [ "$system_type" = "Darwin" ]; then
    sudo sh -c "echo $(which fish) >> /etc/shells"
    chsh -s $(which fish)
elif [ "$system_type" = "Linux" ]; then
    sudo chsh -s $(which fish) $(whoami)
fi
