name: Dotfiles Installation

on:
  push:
  schedule:
    - cron: '0 17 * * 4'
  pull_request:

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13, macos-12, debian-latest, ubuntu-latest]
    steps:
      - name: Clean up installed software
        run: |
          brew uninstall --force --ignore-dependencies $(brew list)
          brew uninstall --cask --force --ignore-dependencies $(brew list --cask)
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
      - name: Clone this repo
        uses: actions/checkout@v3

      - name: Run install script
        run: |
          ./install.sh

      - name: Verify brew Installation
        run: |
          brew doctor
          brew update
          brew upgrade
          brew cleanup
          brew doctor